foreground #d3cede
background #161421
selection_foreground #d3cede
selection_background #2d284c
cursor #d3cede
cursor_text_color #161421
active_border_color #7264cc
inactive_border_color #3d3759
color0 #14121f
color1 #887ad7
color2 #b7ade4
color3 #958ad3
color4 #9f95d5
color5 #9b8de0
color6 #c0b8e2
color7 #d3cede
color8 #2b2840
color9 #a398da
color10 #c2bae2
color11 #aca3d7
color12 #b8b0da
color13 #b6ace0
color14 #cac3e1
color15 #ffffff
