foreground #d5d5e1
background #151622
selection_foreground #d5d5e1
selection_background #263450
cursor #d5d5e1
cursor_text_color #151622
active_border_color #5b8cdc
inactive_border_color #383f5c
color0 #131420
color1 #7478ad
color2 #ae8796
color3 #87a6de
color4 #94aede
color5 #8a6785
color6 #bba0ad
color7 #d5d5e1
color8 #292c41
color9 #9799bf
color10 #bda3b0
color11 #a4b7df
color12 #b3c0df
color13 #ae99ae
color14 #c8b9c4
color15 #ffffff
